// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

public partial class ApplicationDBContext : DbContext
{
    public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<InputDatum> InputData { get; set; }

    public virtual DbSet<PaymentGateway> PaymentGateways { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InputDatum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__InputDat__3214EC07FC337A5B");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.IsRequired).HasDefaultValue(false);

            entity.HasOne(d => d.PaymentGateway).WithMany(p => p.InputData)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InputData_PaymentGateway");
        });

        modelBuilder.Entity<PaymentGateway>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentG__3214EC078CEB4C1B");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}