// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Table("CustomerFlow")]
public partial class CustomerFlow
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(200)]
    public string FieldName { get; set; }

    [Required]
    [StringLength(100)]
    public string FieldType { get; set; }

    public bool IsRequired { get; set; }

    public string Description { get; set; }

    public int? OrderIndex { get; set; }

    public Guid PaymentGatewayId { get; set; }

    public Guid CustomerId { get; set; }

    [StringLength(200)]
    public string GroupName { get; set; }
}