<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Poc.Common\Poc.Common.csproj" />
    <ProjectReference Include="..\Poc.EF\Poc.EF.csproj" />
    <ProjectReference Include="..\Poc.Infrastructure\Poc.Infrastructure.csproj" />
  </ItemGroup>

</Project>
