// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Poc.EF.Entities;

    [Table("Customer")]
public partial class Customer
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(320)]
    public string Email { get; set; }

    [StringLength(15)]
    public string Phone { get; set; }

    [StringLength(15)]
    public string Mobile { get; set; }

    [Required]
    [MaxLength(32)]
    public byte[] Salt { get; set; }

    [Required]
    [MaxLength(64)]
    public byte[] Hash { get; set; }

    public string Reason { get; set; }

    [StringLength(50)]
    public string Country { get; set; }

    [StringLength(200)]
    public string State { get; set; }

    [StringLength(200)]
    public string City { get; set; }

    public string Address { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public bool? Status { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<CustomerBusiness> CustomerBusinesses { get; set; } = new List<CustomerBusiness>();

    [InverseProperty("Customer")]
    public virtual ICollection<ProofOfBusinessActivity> ProofOfBusinessActivities { get; set; } = new List<ProofOfBusinessActivity>();

    [InverseProperty("Customer")]
    public virtual ICollection<ProofOfBusiness> ProofOfBusinesses { get; set; } = new List<ProofOfBusiness>();
}