// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Poc.EF.Entities;

[Table("CustomerBusiness")]
public partial class CustomerBusiness
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Type { get; set; }

    [Required]
    [StringLength(50)]
    public string Country { get; set; }

    [StringLength(200)]
    public string State { get; set; }

    [StringLength(200)]
    public string City { get; set; }

    public string Address { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CeatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    public Guid CustomerId { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("CustomerBusinesses")]
    public virtual Customer Customer { get; set; }
}