// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Poc.EF.Entities;

public partial class InputDatum
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(100)]
    public string FieldName { get; set; }

    [StringLength(50)]
    public string FieldType { get; set; }

    public bool? IsRequired { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public int? OrderIndex { get; set; }

    public Guid PaymentGatewayId { get; set; }

    [ForeignKey("PaymentGatewayId")]
    [InverseProperty("InputData")]
    public virtual PaymentGateway PaymentGateway { get; set; }
}