// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Poc.EF.Entities;  

[Table("PaymentGateway")]
public partial class PaymentGateway
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(200)]
    public string GatewayName { get; set; }

    [InverseProperty("PaymentGateway")]
    public virtual ICollection<InputDatum> InputData { get; set; } = new List<InputDatum>();
}