// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Poc.EF.Entities;

[Table("ProofOfBusiness")]
public partial class ProofOfBusiness
{
    [Key]
    public Guid Id { get; set; }

    public int Type { get; set; }

    [Required]
    public string FileContent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CeatedDate { get; set; }

    public Guid? ModifiedBy { get; set; }

    public Guid CustomerId { get; set; }

    public bool? Status { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("ProofOfBusinesses")]
    public virtual Customer Customer { get; set; }
}