// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Poc.EF.Entities;

[Table("SignUpRequest")]
[Index("Email", Name = "UQ__SignUpRe__A9D10534113C74B9", IsUnique = true)]
public partial class SignUpRequest
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(500)]
    public string Email { get; set; }

    [StringLength(15)]
    public string Phone { get; set; }

    [StringLength(15)]
    public string Mobile { get; set; }

    [Required]
    [MaxLength(32)]
    public byte[] Salt { get; set; }

    [Required]
    [MaxLength(64)]
    public byte[] Hash { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool Status { get; set; }

    public string Reason { get; set; }

    public Guid? ModifiedBy { get; set; }
}