// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Poc.EF.Entities;

namespace Poc.EF.Context;

public partial class ApplicationDBContext : DbContext
{
    public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerBusiness> CustomerBusinesses { get; set; }

    public virtual DbSet<ProofOfBusiness> ProofOfBusinesses { get; set; }

    public virtual DbSet<ProofOfBusinessActivity> ProofOfBusinessActivities { get; set; }

    public virtual DbSet<SignUpRequest> SignUpRequests { get; set; }

    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<InputDatum> InputData { get; set; }

    public virtual DbSet<PaymentGateway> PaymentGateways { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Customer__3214EC07926E8FB0");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Status).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<CustomerBusiness>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Customer__3214EC07D79AFC3F");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerBusinesses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerBusiness_Customer");
        });

        modelBuilder.Entity<ProofOfBusiness>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProofOfB__3214EC074CB2802C");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Status).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.Customer).WithMany(p => p.ProofOfBusinesses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProofOfBusiness_Customer");
        });

        modelBuilder.Entity<ProofOfBusinessActivity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProofOfB__3214EC07D80E35DA");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Status).HasDefaultValue(false);

            entity.HasOne(d => d.Customer).WithMany(p => p.ProofOfBusinessActivities)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProofOfBusinessActivities_Customer");
        });

        modelBuilder.Entity<SignUpRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SignUpRe__3214EC0775BEB417");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Status).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07F5FE79F8");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<InputDatum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__InputDat__3214EC07FC337A5B");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.IsRequired).HasDefaultValue(false);

            entity.HasOne(d => d.PaymentGateway).WithMany(p => p.InputData)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InputData_PaymentGateway");
        });

        modelBuilder.Entity<PaymentGateway>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentG__3214EC078CEB4C1B");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}