// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

public partial class ProofOfBusinessActivity
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Type { get; set; }

    [Required]
    public string Reason { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    public bool Status { get; set; }

    public Guid ModifiedBy { get; set; }

    public Guid CustomerId { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("ProofOfBusinessActivities")]
    public virtual Customer Customer { get; set; }
}